[appendix,obligation="informative"]
[[appendix_b]]
:numbered:
== Annex B: Web API (Normative)
:!numbered:
=== HTTP 1.1


[requirement]
====
[%metadata]
label:: /req/core/http
part:: The server SHALL conform to  http://docs.opengeospatial.org/DRAFTS/17-069r2.html#rfc2616[HTTP 1.1].
part:: If the server supports HTTPS, the server SHALL also conform to  http://docs.opengeospatial.org/DRAFTS/17-069r2.html#rfc2818[HTTP over TLS].
====

This includes the correct use of status codes, headers, etc.

[recommendation]
====
[%metadata]
label:: /rec/core/head
part:: The server SHOULD support the HTTP 1.1 method HEAD for all resources that support the method GET.
====

Supporting the method HEAD in addition to GET can be useful for clients and is simple to implement.

Servers implementing  http://docs.opengeospatial.org/DRAFTS/17-069r2.html#cross_origin[CORS] will implement the method OPTIONS, too.

=== HTTP status codes

This API standard does not impose any restrictions on which features of the HTTP and HTTPS protocols may be used. API clients should be prepared to handle any legal HTTP or HTTPS status codeThe *Status Codes* listed in Table 3 are of particular relevance to implementers of this standard. Status codes 200, 400, and 404 are called out in API requirements. Therefore, support for these status codes is mandatory for all compliant implementations. The remainder of the status codes in Table 3 are not mandatory but are important for the implementation of a well-functioning API. Support for these status codes is strongly encouraged for both client and server implementations.

[#tbl_status_codes]
.Typical HTTP status codes
[width=575]
|===
3+.<| _Typical HTTP status codes_
h| Status Code | Mandatory / Optional | Description
| *200* | *Mandatory* | A successful request.
| 304 | Optional | An  http://docs.opengeospatial.org/DRAFTS/17-069r2.html#web_caching[entity tag was provided in the request] and the resource has not been changed since the previous request.
| *400* | *Mandatory* | The server cannot or will not process the request due to an apparent client error. For example, a query parameter had an incorrect value.
| 401 | Optional | The request requires user authentication. The response includes a WWW-Authenticate header field containing a challenge applicable to the requested resource.
| 403 | Optional | The server understood the request but is refusing to fulfill it. While status code 401 indicates missing or bad authentication, status code 403 indicates that authentication is not the issue, but the client is not authorized to perform the requested operation on the resource.
| *404* | *Mandatory* | The requested resource does not exist on the server. For example, a path parameter had an incorrect value.
| 405 | Optional | The request method is not supported. For example, a POST request was submitted, but the resource only supports GET requests.
| 406 | Optional | The Accept header submitted in the request did not support any of the media types supported by the server for the requested resource.
| 500 | Optional | An internal error occurred in the server.
|===

More specific guidance is provided for each resource, where applicable.


[permission]
====
[%metadata]
label:: /per/core/additional-status-codes
part:: Servers MAY support other capabilities of the HTTP protocol and, therefore, MAY return other status codes than those listed in <<tbl_status_codes>>.
====

The API Description Document describes the HTTP status codes generated by that API. This should not be an exhaustive list of all possible status codes. It is not reasonable to expect an API designer to control the use of HTTP status codes which are not generated by their software. Therefore, it is recommended that the API Description Document limit itself to describing HTTP status codes relevant to the proper operation of the API application logic. Client implementations should be prepared to receive HTTP status codes in addition to those described in the API Description Document.

=== Unknown or invalid query parameters


[requirement]
====
[%metadata]
label:: /req/core/query-param-unknown
part:: The server SHALL respond with a response with the status code 400, if the request URI includes a query parameter that is not specified in the API definition.
====


If a server wants to support vendor specific parameters, these must be explicitly declared in the API definition.

If OpenAPI is used to represent the API definition, a capability exists to allow additional parameters without explicitly declaring them. That is, parameters that have not been explicitly specified in the API definition for the operation will be ignored.

OpenAPI schema for additional "free-form" query parameters

[source%unnumbered,yaml]
----
in: query
name: vendorSpecificParameters
schema:
  type: object
  additionalProperties: true
style: form
----

Note that the name of the parameter does not matter as the actual query parameters are the names of the object properties. For example, assume that the value of vendorSpecificParameters is this object:

[source%unnumbered,json]
----
{
  "my_first_parameter": "some value",
  "my_other_parameter": 42
}
----

In the request URI this would be expressed

as `&my_first_parameter=some%20value&my_other_parameter=42`.


[requirement]
====
[%metadata]
label:: /req/core/query-param-invalid
part:: The server SHALL respond with a response with the status code 400, if the request URI includes a query parameter that has an invalid value.
====

This is a general rule that applies to all parameters, whether they are specified in this document or in additional parts. A value is invalid, if it violates the API definition or any other constraint for that parameter stated in a requirement.

=== Web caching

Entity tags are a mechanism for web cache validation and for supporting conditional requests to reduce network traffic. Entity tags are specified by [HTTP/1.1 (RFC 2616)].

[recommendation]
====
[%metadata]
label:: /rec/core/etag
part:: The service SHOULD support entity tags and the associated headers as specified by HTTP/1.1.
====


=== Support for cross-origin requests

Access to data from a HTML page is by default prohibited for security reasons if the data is located on another host than the webpage ("same-origin policy"). A typical example is a web-application accessing feature data from multiple distributed datasets.


[recommendation]
====
[%metadata]
label:: /rec/core/cross-origin
part:: If the server is intended to be accessed from the browser, cross-origin requests SHOULD be supported. Note that support can also be added in a proxy layer on top of the server.
====

Two common mechanisms to support cross-origin requests are:

* https://en.wikipedia.org/wiki/Cross-origin_resource_sharing[Cross-origin resource sharing (CORS)]
* https://en.wikipedia.org/wiki/JSONP[JSONP (JSON with padding)]
