== Scope

The OGC API - 3D GeoVolumes candidate Standard specifies an Application Programming Interface (API) and encoding that organizes access to a variety of 3D content according to a
hierarchy of 3D geospatial volumes (GeoVolumes). The goal of the candidate Standard is to allow applications to request a variety of 3D content from different providers in an
interoperable and standardized way.

OGC API - 3D GeoVolumes is based on Open Geospatial Consortium (OGC) and OpenAPI principles. The API is consistent with OGC API – Common – Part 1: Core building blocks and
supports link-follow, bounding box query, and tile coordinate methods of access to resources of interest.

The objective of the 3D GeoVolumes API and resource model is not to replace existing distribution methods and models for 3D content such as OGC 3D Tiles and I3S, but to enable
interoperability between them.

The content provided within this document is derived largely from work done during collaborative, hands-on engineering conducted by members of the OGC during late 2019 and
early 2020.
