[[clause_requirements_class_core]]
== Requirements Class "Core"

The "Core" requirements class of OGC API - 3D GeoVolumes specifies that a collection of 3D geospatial data is accessible
from an OGC API collection (as defined in https://docs.ogc.org/DRAFTS/20-024.html[OGC API - Common - Part 2: Geospatial Data])
using one or more access mechanisms defined in the additional requirements classes of this standard.
Additionally, implementations are recommended to conform the https://www.opengis.net/spec/ogcapi-common-1/1.0/req/landing-page[Landing Page requirements class] of
https://docs.ogc.org/is/19-072/19-072.html[OGC API - Common - Part 1: Core], defining a mechanism to share the list of supported conformance classes as well
as requiring the provision of an API definition.

[[rc_core]]

[requirements_class]
====
[%metadata]
label:: http://www.opengis.net/spec/ogcapi-geovolumes-1/1.0/req/core
subject:: Web API
inherit:: https://www.opengis.net/spec/ogcapi-common-1/1.0/req/core
inherit:: https://www.opengis.net/spec/ogcapi-common-2/1.0/req/collections
====

A sample landing page response document of an GeoVolumes API is provided below.

[source%unnumbered,json]
----
{
"title": "OGC 3D Pilot",
"description": "A Pilot of an API for GeoVolumes",
"links": [
    {
      "href": " http://data.example.org/[http://data.example.org/]",
      "rel": "service-desc",
      "type": "application/json",
      "title": "Service Description"
    },
    {
      "href": " http://data.example.org/api[http://data.example.org/api]",
      "rel": "service",
      "type": "application/json",
      "title": "the API definition"
    },
    {
      "href": " http://data.example.org/conformance[http://data.example.org/conformance]",
      "rel": "conformance",
      "type": "application/json",
      "title": "Conformance"
    },
    {
      "href": " http://data.example.org/collections[http://data.example.org/collections]",
      "rel": "data",
      "type": "application/json",
      "title": "Collections"
    }
  ]
}
----

[[conformance_declaration_clause]]
=== Declaration of Conformance Classes

The Conformance Declaration states the conformance classes from standards or community specifications, identified by a URI, to which the API conforms.
The conformance resource requires no parameters. The HTTP `/conformance` GET response returns the list of URIs of conformance classes implemented by the server in JSON.

[requirement]
====
[%metadata]
label:: /req/core/conformance
part:: If the API instance has a mechanism to advertise conformance classes, the list of conformance classes SHALL include the ones defined in this Standard and listed in
part:: If some conformance classes of this Standard are only supported by particular collections, requirements classes supported by these collections SHALL be listed in a
resource linked to from the collection description as described in the
https://docs.ogc.org/DRAFTS/20-024.html#per_collections_conformance[OGC API - Common - Part 2 per-collection conformance permission].
====

The following example of the conformance declaration of a 3D GeoVolumes API instance supporting all of the access mechanisms defined in the different requirements classes:

[source%unnumbered,json]
----
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/json",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/landing-page",
    "http://www.opengis.net/spec/ogcapi-common-1/1.0/conf/oas30",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/collections",
    "http://www.opengis.net/spec/ogcapi-common-2/1.0/conf/json",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets-list",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/core"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tileset"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geodata-tilesets"
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/tilesets-list",
    "http://www.opengis.net/spec/ogcapi-tiles-1/1.0/conf/geojson",
    "http://www.opengis.net/spec/ogcapi-geovolumes-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-geovolumes-1/1.0/conf/3d-tiles",
    "http://www.opengis.net/spec/ogcapi-geovolumes-1/1.0/conf/i3s",
    "http://www.opengis.net/spec/ogcapi-geovolumes-1/1.0/conf/2dtms-tiles",
    "http://www.opengis.net/spec/ogcapi-geovolumes-1/1.0/conf/point-tiles",
    "http://www.opengis.net/spec/ogcapi-geovolumes-1/1.0/conf/batched-3d-models-tiles"
  ]
}
----

[[collections_clause]]
=== Collections

[requirement]
====
[%metadata]
label:: /req/core/collections
part:: Any collection supporting this OGC API - 3D GeoVolumes Standard SHALL have 3-dimensional bounding boxes in their spatial extent .
part:: Any collection supporting this OGC API - 3D GeoVolumes Standard SHALL include a link in its `links` array to at least one of the access mechanism
defined in one of the requirements classes defined in this Standard, using the associated link relation and media type: +
+
* 3D Tiles: `"type": "application/json+3dtiles", "rel": "[ogc-rel:3d-geovolumes]"`,
* i3s: `"type": "application/vnd.esri.i3s.json+gzip", "rel": "[ogc-rel:3d-geovolumes]"`,
* Tiled Points Referencing 3D Models: `"type": "application/json", "rel": "[ogc-rel:tilesets-vector]"` (also link template for 3D models),
* Batched 3D Models: `"type": "application/json", "rel": "[ogc-rel:tilesets-3dmodels]"`
====
