[[conventions]]
== Conventions

This section provides details and examples for conventions used in this document.


=== Identifiers

The normative provisions in this specification are denoted by the URI

http://www.opengis.net/spec/{standard}/{m.n}

All requirements and conformance tests that appear in this document are denoted by partial URIs which are relative to this base.

=== Link Relation Type (Rel)

This defines the relationship between the current JSON resource representation and a related JSON resource. For more information see:

* Link Relations [http://docs.opengeospatial.org/is/17-069r3/17-069r3.html%23_link_relations[http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_link_relations]]
* IANA: Link Relation Types [https://www.iana.org/assignments/link-relations/link-relations.xml[https://www.iana.org/assignments/link-relations/link-relations.xml]]


The following enumeration is provided as an example. Other relationship types are possible.

* affinemap: Link from a 3D-Container with 2D content to a 3D-Container with 2.5D content (surface, point cloud) to which the 2D content should be texture-mapped.
* alternate: Refers to a substitute for this context.
* collections: The target points to a 3D-container resource which represents the collection resource for the context.
* conformance: Refers to a resource that identifies the specifications that the link's context conforms to.
* data: Indicates that the link's context is a distribution of a dataset that is an API and refers to the root resource of the dataset in the API.
* dataset: Indicates that the link's context is a distribution of a dataset that is an API and refers to the root resource of the dataset in the API.
* describedby: Refers to a resource providing information about the link's context.
* distribution: Indicates that the link's context is a distribution.
* item: The target IRI points to a resource that is a member of the collection represented by the context IRI.
* items: Refers to a resource that is comprised of members of the collection represented by the link's context.
* original: The distribution representing the most original version of the dataset, e.g. a CityGML model.
* parent: link to enclosing 3D-Container.
* root: link to top-level 3D-Container.
* scheme: link to the definition of any implicit tile scheme which sets the 3D-Container organization, extent and/or addressing.
* self: Conveys an identifier for the link's context.
* service: Indicates a URI that can be used to retrieve a service document.
* service-desc: Identifies service description for the context that is primarily intended for consumption by machines.

=== Media Types

A table of the media types relevant to this standard follows.

[#media-types,reftext='{table-caption} {counter:table-num}']
.Media Types relevant to OGC API - 3D GeoVolumes
[width="90%",cols="2,4"]
|====
^|*media type*                        ^|*description*
|`text/html`                           |Supported to present browser-friendly metadata resources
|`application/json`                    |Used for landing page, conformance, collection description, OGC API - Tiles tilesets list and tilesets metadata
|`application/3dtiles+json`            |Used for 3D Tiles Bounding Volume Hierarchy tilesets
|`application/vnd.esri.i3s.json+gzip`  |Used for i3s Tiles Bounding Volume Hierarchy tilesets
|`model/gltf-binary`                   |Used for 3D Models (whether batched 3D models, referenced 3D models, or glTF content linked from 3D Tiles 1.1+ tilesets)
|`text/geo+json`                       |Tiled Point Vector Data GeoJSON encoding option for tiles referencing 3D models
|`application/vnd.mapbox-vector-tile`  |Tiled Point Vector Data Mapbox Vector Tiles encoding option for tiles referencing 3D models
|====
