[[ats_core_fc-md-op]]
[abstract_test]
====
[%metadata]
label:: /conf/core/fc-md-op
subject:: <<req_core_collections-op,/req/core/collections-op>>,<<req_core_collections-success,/req/core/collections-success>>
test-purpose:: Verify that the collections resources can be fetched.

[.component,class=test method]
=====
[.component,class=step]
--
Issue an HTTP GET request to the path /collections with header Accept: application/json.
--

[.component,class=step]
--
Issue an HTTP GET request to the path /collections?f=json.
--

[.component,class=step]
--
Issue an HTTP GET request to the path `/collections?bbox=x1,y1,{z1},x2,y2,{z2}.
--

[.component,class=step]
--
Validate that the response has a status code 200.
--

[.component,class=step]
--
Validate the contents of the returned document against the schema in: /collections, item E.
--

[.component,class=step]
--
Verify that each container id #/collections/{i} (where {i} is the index of the style in the array) is unique.
--

[.component,class=step]
--
Verify that each collection has at least one link with rel=self.
--

[.component,class=step]
--
Verify that for each link with rel=self that the href value links to a resource at the path /collections/{3DContainerId} where {3DContainerId} is the id member of the 3d Container.
--

[.component,class=step]
--
If each collection has content greater than one, verify each content contains rel=original or rel=alternate
--
=====
====
